development:
  secret_key_base: 9ac2d0ad8ebcc312090e69d745006d3cf8
  secret_token: 9ac2d0ad8ebcc312090e69d745006d3cf8
  admin_email: "me@example.com"
  admin_password: "password"

production:
  secret_key_base: 9ac2d0ad8ebcc312090e69d745006d3cf8
  secret_token: 9ac2d0ad8ebcc312090e69d745006d3cf8
  admin_email: <%= ENV['ADMIN_MAIL'] %>
  admin_password: <%= ENV['ADMIN_PASSWORD'] %>
